---
development:
  cloud_name: dtonjl2fx
  api_key: '628551373332451'
  api_secret: lCqxprR69qzR6N0ygecRdZuFr18
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dtonjl2fx
  api_key: '628551373332451'
  api_secret: lCqxprR69qzR6N0ygecRdZuFr18
  enhance_image_tag: true
  static_image_support: true
  CLOUDINARY_URL=cloudinary://628551373332451:lCqxprR69qzR6N0ygecRdZuFr18@dtonjl2fx
test:
  cloud_name: dtonjl2fx
  api_key: '628551373332451'
  api_secret: lCqxprR69qzR6N0ygecRdZuFr18
  enhance_image_tag: true
  static_image_support: false
